@endpoint = http://localhost:8080/api/v1


GET {{endpoint}}/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VyTmFtZSI6InRlc3QiLCJpYXQiOjE3MzgwMTgyMjAsImV4cCI6MTczODEwNDYyMH0.4jpE2uWoWGCeG6DgP2UPR1hiNsp0rlLW-JwPx8ANZks

###

POST {{endpoint}}/transactions/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VyTmFtZSI6InRlc3QiLCJpYXQiOjE3MzgwMTgyMjAsImV4cCI6MTczODEwNDYyMH0.4jpE2uWoWGCeG6DgP2UPR1hiNsp0rlLW-JwPx8ANZks

{
    "type" : "Income",
    "amount" : 1500,
    "date" : "2025-1-11",
    "description" : "Charlis Cafe"
}


###

DELETE {{endpoint}}/transactions/delete/678f19a7cad3b240c4622f3d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VyTmFtZSI6InRlc3QiLCJpYXQiOjE3MzgwMTgyMjAsImV4cCI6MTczODEwNDYyMH0.4jpE2uWoWGCeG6DgP2UPR1hiNsp0rlLW-JwPx8ANZks

###
DELETE {{endpoint}}/transactions/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VyTmFtZSI6InRlc3QiLCJpYXQiOjE3MzgwMTgyMjAsImV4cCI6MTczODEwNDYyMH0.4jpE2uWoWGCeG6DgP2UPR1hiNsp0rlLW-JwPx8ANZks

{
    "transactions" : [
        "678f19aacad3b240c4622f40"
    ]
}