@endpoint = https://finance-tracker-backend-js79.onrender.com/api/v1

GET {{endpoint}}/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwcmFzaHJpamFuQGdtYWlsLmNvbSIsInVzZXJOYW1lIjoicmVhZCIsImlhdCI6MTczODU0OTg5NSwiZXhwIjoxNzM4NjM2Mjk1fQ.Hw3ihVHQv-rng5t2jUbG6wjKqeZnE3A0GavPOw-VgOI

###

POST {{endpoint}}/transactions/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwcmFzaHJpamFuQGdtYWlsLmNvbSIsInVzZXJOYW1lIjoicmVhZCIsImlhdCI6MTczODU0OTg5NSwiZXhwIjoxNzM4NjM2Mjk1fQ.Hw3ihVHQv-rng5t2jUbG6wjKqeZnE3A0GavPOw-VgOI

{
    "type" : "Expense",
    "amount" : 3000,
    "date" : "2025-1-11",
    "description" : "Charlis Cafe"
}


###

DELETE {{endpoint}}/transactions/delete/678f19a7cad3b240c4622f3d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwcmFzaHJpamFuQGdtYWlsLmNvbSIsInVzZXJOYW1lIjoicmVhZCIsImlhdCI6MTczODU0OTg5NSwiZXhwIjoxNzM4NjM2Mjk1fQ.Hw3ihVHQv-rng5t2jUbG6wjKqeZnE3A0GavPOw-VgOI

###
DELETE {{endpoint}}/transactions/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNwcmFzaHJpamFuQGdtYWlsLmNvbSIsInVzZXJOYW1lIjoicmVhZCIsImlhdCI6MTczODU0OTg5NSwiZXhwIjoxNzM4NjM2Mjk1fQ.Hw3ihVHQv-rng5t2jUbG6wjKqeZnE3A0GavPOw-VgOI

{
    "transactions" : [
        "678f19aacad3b240c4622f40"
    ]
}

###

PATCH {{endpoint}}/transactions/update/67984559834f680a2adc95d6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VyTmFtZSI6InRlc3QiLCJpYXQiOjE3MzgwMTgyMjAsImV4cCI6MTczODEwNDYyMH0.4jpE2uWoWGCeG6DgP2UPR1hiNsp0rlLW-JwPx8ANZks

{
    "amount" : 2000 
}